version: '3'

services:

  broker-services:
    build:
      context: ./../broker-services
      dockerfile: ./../broker-services/broker-services.dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1